# Project 3: Data Cleaning

## Oasis Infobyte Data Analytics Internship

### Objective
The objective of this project is to clean and prepare a messy dataset for analysis. The project includes identifying missing values, duplicate records, inconsistent formatting, incorrect data types, and outliers.

### Tools and Technologies
- Python
- Pandas
- NumPy
- Jupyter Notebook

In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv("archive (2)/my_file (1).csv")

df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Rank                              20 non-null     int64
 1   Peak                              9 non-null      str
 2   All Time Peak                     6 non-null      str
 3   Actual gross                      20 non-null     str
 4   Adjusted gross (in 2022 dollars)  20 non-null     str
 5   Artist                            20 non-null     str
 6   Tour title                        20 non-null     str
 7   Year(s)                           20 non-null     str
 8   Shows                             20 non-null     int64
 9   Average gross                     20 non-null     str
 10  Ref.                              20 non-null     str
dtypes: int64(2), str(9)
memory usage: 1.8 KB

In [7]:
df.isnull().sum()

Rank                                 0
Peak                                11
All Time Peak                       14
Actual gross                         0
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           0
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                 0
dtype: int64

In [8]:
df[df["Peak"].isnull() | df["All Time Peak"].isnull()]

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]
6,7,2[10],NaN,"$280,000,000","$381,932,682",Celine Dion,Taking Chances World Tour,2008–2009,131,"$2,137,405",[11]
7,7,NaN,NaN,"$257,600,000","$257,600,000",Pink,Summer Carnival †,2023–2024,41,"$6,282,927",[12]
8,9,NaN,NaN,"$256,084,556","$312,258,401",Beyoncé,The Formation World Tour,2016,49,"$5,226,215",[13]
9,10,NaN,NaN,"$250,400,000","$309,141,878",Taylor Swift,The 1989 World Tour,2015,85,"$2,945,882",[14]
10,11,NaN,NaN,"$229,100,000[b]","$283,202,896",Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,"$1,735,606",[15][16]
11,12,NaN,14[17],"$227,400,000","$295,301,479",Lady Gaga,The Monster Ball Tour *,2009–2011,203,"$1,118,227",[18]
12,13,NaN,NaN,"$204,000,000","$251,856,802",Katy Perry,Prismatic World Tour,2014–2015,151,"$1,350,993",[19]
13,14,1[20],NaN,"$200,000,000","$299,676,265",Cher,Living Proof: The Farewell Tour ‡[21][a],2002–2005,325,"$615,385",[20]
14,15,2[c],NaN,"$194,000,000","$281,617,035",Madonna,Confessions Tour,2006,60,"$3,233,333",[5]
15,16,NaN,NaN,"$184,000,000","$227,452,347",Pink,The Truth About Love Tour,2013–2014,142,"$1,295,775",[22]
16,17,NaN,NaN,"$170,000,000","$213,568,571",Lady Gaga,Born This Way Ball,2012–2013,98,"$1,734,694",[d]
17,18,NaN,NaN,"$169,800,000","$207,046,755",Madonna,Rebel Heart Tour,2015–2016,82,"$2,070,732",[4]
18,19,NaN,NaN,"$167,700,000[e]","$204,486,106",Adele,Adele Live 2016,2016–2017,121,"$1,385,950",[25]
19,20,NaN,NaN,"$150,000,000","$185,423,109",Taylor Swift,The Red Tour,2013–2014,86,"$1,744,186",[26]

In [9]:
print("Peak column:")
print(df["Peak"].unique())

print("\nAll Time Peak column:")
print(df["All Time Peak"].unique())

Peak column:
<StringArray>
['1', '1[4]', '2[7]', '2[4]', '2[10]', nan, '1[20]', '2[c]']
Length: 8, dtype: str

All Time Peak column:
<StringArray>
['2', '7[2]', '2[5]', '10[7]', nan, '10[9]', '14[17]']
Length: 7, dtype: str

In [10]:
df["Peak"] = df["Peak"].fillna("Not Available")
df["All Time Peak"] = df["All Time Peak"].fillna("Not Available")

df.isnull().sum()

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.columns = df.columns.str.replace("\xa0", " ", regex=False)
df.columns = df.columns.str.strip()

print(df.columns)

Index(['Rank', 'Peak', 'All Time Peak', 'Actual gross',
       'Adjusted gross (in 2022 dollars)', 'Artist', 'Tour title', 'Year(s)',
       'Shows', 'Average gross', 'Ref.'],
      dtype='str')

In [13]:
print(df["Actual gross"].head())
print(df["Adjusted gross (in 2022 dollars)"].head())
print(df["Average gross"].head())

0    $780,000,000
1    $579,800,000
2    $411,000,000
3    $397,300,000
4    $345,675,146
Name: Actual gross, dtype: str
0    $780,000,000
1    $579,800,000
2    $560,622,615
3    $454,751,555
4    $402,844,849
Name: Adjusted gross (in 2022 dollars), dtype: str
0    $13,928,571
1    $10,353,571
2     $4,835,294
3     $2,546,795
4     $6,522,173
Name: Average gross, dtype: str

In [15]:
gross_columns = [
    "Actual gross",
    "Adjusted gross (in 2022 dollars)",
    "Average gross"
]

for column in gross_columns:
    df[column] = (
        df[column]
        .astype(str)
        .str.replace("$", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    
    df[column] = pd.to_numeric(df[column], errors="coerce")

df[gross_columns].head()

   Actual gross  Adjusted gross (in 2022 dollars)  Average gross
0   780000000.0                         780000000       13928571
1   579800000.0                         579800000       10353571
2   411000000.0                         560622615        4835294
3   397300000.0                         454751555        2546795
4   345675146.0                         402844849        6522173

In [16]:
df[gross_columns].isnull().sum()

Actual gross                        2
Adjusted gross (in 2022 dollars)    0
Average gross                       0
dtype: int64

In [17]:
df[df["Actual gross"].isnull()]

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
10,11,Not Available,Not Available,NaN,283202896,Beyoncé,The Mrs. Carter Show World Tour,2013–2014,132,1735606,[15][16]
18,19,Not Available,Not Available,NaN,204486106,Adele,Adele Live 2016,2016–2017,121,1385950,[25]

In [18]:
median_gross = df["Actual gross"].median()

df["Actual gross"] = df["Actual gross"].fillna(median_gross)

df["Actual gross"].isnull().sum()

np.int64(0)

In [19]:
df["Peak"] = df["Peak"].astype(str).str.extract(r"(\d+)")[0]
df["All Time Peak"] = df["All Time Peak"].astype(str).str.extract(r"(\d+)")[0]

print(df[["Peak", "All Time Peak"]].head(10))

  Peak All Time Peak
0    1             2
1    1             7
2    1             2
3    2            10
4    2           NaN
5    2            10
6    2           NaN
7  NaN           NaN
8  NaN           NaN
9  NaN           NaN

In [20]:
df["Peak"] = df["Peak"].fillna("Not Available")
df["All Time Peak"] = df["All Time Peak"].fillna("Not Available")

df[["Peak", "All Time Peak"]].head(10)

            Peak  All Time Peak
0              1              2
1              1              7
2              1              2
3              2             10
4              2  Not Available
5              2             10
6              2  Not Available
7  Not Available  Not Available
8  Not Available  Not Available
9  Not Available  Not Available

In [22]:
df["Year(s)"].unique()

<StringArray>
['2023–2024',      '2023', '2008–2009', '2018–2019',      '2018',      '2012',
      '2016',      '2015', '2013–2014', '2009–2011', '2014–2015', '2002–2005',
      '2006', '2012–2013', '2015–2016', '2016–2017']
Length: 16, dtype: str

In [23]:
df["Start Year"] = df["Year(s)"].str.extract(r"(\d{4})")[0]

df["End Year"] = df["Year(s)"].str.extract(
    r"–(\d{4})"
)[0]

# If there is no end year, use the start year
df["End Year"] = df["End Year"].fillna(df["Start Year"])

# Convert both columns to numeric
df["Start Year"] = df["Start Year"].astype(int)
df["End Year"] = df["End Year"].astype(int)

df[["Year(s)", "Start Year", "End Year"]].head(10)

     Year(s)  Start Year  End Year
0  2023–2024        2023      2024
1       2023        2023      2023
2  2008–2009        2008      2009
3  2018–2019        2018      2019
4       2018        2018      2018
5       2012        2012      2012
6  2008–2009        2008      2009
7  2023–2024        2023      2024
8       2016        2016      2016
9       2015        2015      2015

In [24]:
df.isnull().sum()

Rank                                0
Peak                                0
All Time Peak                       0
Actual gross                        0
Adjusted gross (in 2022 dollars)    0
Artist                              0
Tour title                          0
Year(s)                             0
Shows                               0
Average gross                       0
Ref.                                0
Start Year                          0
End Year                            0
dtype: int64

In [25]:
df.describe()

,Rank,Actual gross,Adjusted gross (in 2022 dollars),Shows,Average gross,Start Year,End Year
count,20.000000,2.000000e+01,2.000000e+01,20.000000,2.000000e+01,20.00000,20.000000
mean,10.450000,2.934351e+08,3.438781e+08,110.000000,3.726571e+06,2013.85000,2014.700000
std,5.942488,1.535916e+08,1.514627e+08,66.507617,3.393340e+06,5.62209,5.332127
min,1.000000,1.500000e+08,1.854231e+08,41.000000,6.153850e+05,2002.00000,2005.000000
25%,5.750000,1.985000e+08,2.457557e+08,59.000000,1.647508e+06,2011.25000,2011.750000
50%,10.500000,2.532423e+08,2.974889e+08,87.000000,2.342100e+06,2013.50000,2014.500000
75%,15.250000,3.152876e+08,3.924451e+08,134.500000,4.933024e+06,2016.50000,2017.250000
max,20.000000,7.800000e+08,7.800000e+08,325.000000,1.392857e+07,2023.00000,2024.000000

In [26]:
numeric_columns = [
    "Actual gross",
    "Adjusted gross (in 2022 dollars)",
    "Shows",
    "Average gross"
]

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]

    print(f"\n{column}: {len(outliers)} possible outlier(s)")

Actual gross: 2 possible outlier(s)

Adjusted gross (in 2022 dollars): 1 possible outlier(s)

Shows: 1 possible outlier(s)

Average gross: 2 possible outlier(s)

### Outlier Analysis

The IQR method was used to identify possible outliers in the numerical columns. Some possible outliers were detected in revenue and show-related variables.

These values were not removed because the dataset represents real concert tour performance, and unusually high revenue or a high number of shows may represent genuine successful tours rather than data errors.

In [27]:
df.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.,Start Year,End Year
0,1,1,2,780000000.0,780000000,Taylor Swift,The Eras Tour †,2023–2024,56,13928571,[1],2023,2024
1,2,1,7,579800000.0,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3],2023,2023
2,3,1,2,411000000.0,560622615,Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,4835294,[6],2008,2009
3,4,2,10,397300000.0,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7],2018,2019
4,5,2,Not Available,345675146.0,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8],2018,2018

In [28]:
df.to_csv("Cleaned_Concert_Tours_Data.csv", index=False)

In [29]:
import os
os.listdir()

['.ipynb_checkpoints',
 'archive (2)',
 'archive (2).zip',
 'Cleaned_Concert_Tours_Data.csv',
 'Data_Cleaning_Project.ipynb']

# Conclusion

This project focused on cleaning and preparing a concert tours dataset for further analysis.

The following data-cleaning steps were performed:

- Checked the dataset structure and data types.
- Identified and handled missing values.
- Checked for duplicate records.
- Cleaned and standardized column names.
- Converted gross-related columns from text format to numeric format.
- Removed unnecessary reference markers from the Peak and All Time Peak columns.
- Created separate Start Year and End Year columns from the Year(s) column.
- Identified possible outliers using the IQR method.
- Retained valid outliers because they may represent genuine high-performing concert tours.
- Saved the final cleaned dataset as a new CSV file.

After the cleaning process, the dataset became more structured, consistent, and suitable for further analysis and visualization.